### ISSUE TITLE
Unable to compile ExpressivePixelsMinimal Example, missing EPXPlatform_Runtime

### ISSUE THREAD

**Issue by brentru** [microsoft/ExpressivePixels#6]
@GJSea I'm attempting to compile the ExpressivePixelsMinimal example for an Adafruit Matrix Portal M4 (https://www.adafruit.com/product/4745) and am running into the following error:
```
In file included from /Users/brentrubell/Documents/Arduino/libraries/ExpressivePixelsCore/CDisplayArray.h:10,
                 from /Users/brentrubell/Documents/Arduino/libraries/ExpressivePixelsCore/CAnimationManager.h:8,
                 from /Users/brentrubell/Desktop/github_brentru/ExpressivePixels/Firmware/Arduino/Examples/ExpressivePixelsMinimal/ExpressivePixels/ExpressivePixels.ino:3:
/Users/brentrubell/Documents/Arduino/libraries/ExpressivePixelsCore/CLEDDriverBase.h:7:10: fatal error: EPXPlatform_Runtime.h: No such file or directory
    7 | #include "EPXPlatform_Runtime.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.```

I have copied the ExpressivePixelsCore/ folder into my Arduino libraries directory. `EPXPlatform_Runtime` does not seem to be part of this.

Since this is a newer Adafruit board - what Adafruit board and matrix have you built this with? I may be able to try replicating your build process.

**Comment by GJSea** [comment]
Hi Brent, I just updated the Arduino library [here](https://github.com/microsoft/ExpressivePixels/tree/master/Firmware/Arduino) which you can unzip and copy, or try and Install the regular Arduino IDE way - make sure any existing ExpressivePixels folders have been deleted in the Arduino libraries folder. The Minimal Arduino library is self-contained and doesn't require you to copy the ExpressivePixelsCore folder over to the Arduino libraries directory.

**Comment by brentru** [comment]
@GJSea  I'll try it! What hardware combination were you using to test?

**Comment by GJSea** [comment]
@brentru I was using a CircuitPlayground Express with a 16x16 WS2812 display attached on PIN_A2. The Matrix Portal requires a different ExpressivePixels driver that I created a driver for.. I just updated with repo again with an updated Arduino Library plus the driver files as source. Replace CAdafruitDotStar_EPXDriver *pDotStarDriver = new CAdafruitDotStar_EPXDriver with the new CAdafruitRGBMatrix_EPXDriver(...) equivalent in ExpressivePixels.ino

**Comment by brentru** [comment]
@GJSea  Sweet! I'll try it tomorrow and let you know.

**Comment by brentru** [comment]
@GJSea  For the MatrixPortal - should I replace the matching driver files in ExpressivePixelsMinimal.zip with the files you just uploaded in that directory?

**Comment by GJSea** [comment]
@brentru the source files are the same, I uploaded them separately so they could be browsed outside of the Zip. There's still a little bit of patching up to do with CAdafruitRGBMatrix_EPXDriver which I minimally got working, but the main SetPixel function does what it's meant to do with the other ExpressivePixel classes.

**Comment by brentru** [comment]
@GJSea  Ok! Where is `#include <RGBmatrixPanel.h> // Hardware-specific library` from? Which library?

**Comment by GJSea** [comment]
Yup, that's the one!

**Comment by brentru** [comment]
@GJSea Ok - getting closer. Thanks for your patience and help!

The RGBMatrix driver [references pin A5](https://github.com/microsoft/ExpressivePixels/blob/master/Firmware/Arduino/AdafruitRGBMatrix_EPXDriver.cpp#L13). This pin isn't a pin on the MatrixPortal (see: https://learn.adafruit.com/adafruit-matrixportal-m4/pinouts#analog-connector-slash-pins-3072800-21) and will fail when building like:
```
AdafruitRGBMatrix_EPXDriver.cpp:13:13: error: 'A5' was not declared in this scope; did you mean 'A4'?
   13 | #define A   A5
```

**Comment by GJSea** [comment]
Ahh, what I need to do is pull those #defined pin assignments into the constructor and dynamically allocate the Adafruit class... I'll do this tonight... for now you can manually replace those with the new device's pins...

**Comment by brentru** [comment]
We should also replace the RGBMatrix library with the newer Protomatter (https://github.com/adafruit/Adafruit_Protomatter/) library to support more hardware targets. I just tested it this AM, will be adding into the driver more today and PR'ing.

**Comment by brentru** [comment]
@GJSea  Ok, I had a fun day. Filled in the the AdafruitRGBMatrix_EPXDriver class. Now it's using protomatter so this project can support future hardware utilizing this library.  I added the ability to detect board variants during compile (if we're using protomatter rgb matrixes) so we don't need to define pins.

Would you accept me adding a configuration file, `config.h`, to be imported by `ExpressivePixels.ino`. It'd allow the user to `#define` their hardware type(s) outside of the sample sketch. Otherwise, the sample sketch (https://github.com/brentru/ExpressivePixels/blob/master/Firmware/Arduino/Examples/ExpressivePixelsMinimal/ExpressivePixels.ino) grows quite large and becomes difficult to read once we support all the board variants (https://github.com/adafruit/Adafruit_Protomatter/blob/master/examples/simple/simple.ino#L23).

**Comment by GJSea** [comment]
@brentru  Awesome! Might you be able to put the config.h include within a #ifdef ADAFRUIT_RGBMATRIX so it isn't a dependency for other LED drivers? See the latest Push I did for how I incorporated Adafruit's RGBMatrix library.

**Comment by GJSea** [comment]
@brentru It'd be great to see some awesome 64x32 animations on that display, the ExpressivePixels authoring app can import standard GIFs to make starting much easier for that resolution. Let me get the whole ExpressivePixels stack running on Matrix Portal M4, that way you can do live editing and control from the authoring app over USB. The firmware supports triggering of animations via GPIO buttons etc so wearable toggles can light the display up in different ways.

**Comment by brentru** [comment]
Yep, the rgbmatrix will be included rather than hardcoded. I based it off
your commit, see my branch above.

**Comment by brentru** [comment]
@GJSea  Ok, added a PR. 

The boot animation displays strangely on the 64x32 matrix, was it designed as a 16x16 animation? Does the Windows app support a 64x32 matrix?

**Comment by GJSea** [comment]
@brentru the full firmware ExpressivePixelsCore + Platform_xyz (non minimal) is required for the entire communication and storage stack for the authoring app to connect and control. I'm getting a MatrixPortal early next week so will do the port for you then and push it to the Repo.

**Comment by GJSea** [comment]
@brentru responding to your PR comment, yes the Authoring App supports the 64x32 resolution, you'd create an animation in that size, then when you 'Copy Programmable C++ binary to clipboard' specify the 64x32 resolution and pop it into the boot animation array. Alternatively wait for me to port the whole firmware experience to the MatrixPortal and it'll work seamlessly from the app.

**Comment by GJSea** [comment]
@brentru I noticed a little discrepancy in the number of parameters in the CAdafruitRGBMatrix_EPXDriver constructor: in the CPP file there is just width and height, whereas in the Header file is the full set of additional pin parameters aswell.

**Comment by brentru** [comment]
> Alternatively wait for me to port the whole firmware experience to the MatrixPortal and it'll work seamlessly from the app.
I'll wait. Thank you for doing this!

> CAdafruitRGBMatrix_EPXDriver constructor: in the CPP file there is just width and height, whereas in the Header file is the full set of additional pin parameters aswell.
Could we move this to the PR section for a review? I have a reason I did it that way, but let's talk there.

**Comment by GJSea** [comment]
Going through the PR I noticed the header has the correct 2 parameters, not sure why looking at the header by browsing the branch showed the older version…

**Comment by GJSea** [comment]
@brentru I've managed to get the full ExpressivePixels stack working on the Matrix Portal and it is ***simply awesome***!! Can you email me using the address listed in my GitHub profile and I can share videos of the whole setup etc...

**Comment by brentru** [comment]
@GJSea  Just did!
