### ISSUE TITLE
No such file SEGGER_RTT.h when building for Matrix Portal M4

### ISSUE THREAD

**Issue by brentru** [microsoft/ExpressivePixels#8]
@GJSea  Heya, I'm attempting to build for Adafruit Matrix Portal M4 using instructions here (https://github.com/microsoft/ExpressivePixels/wiki/Firmware-for-Arduino-Adafruit-Matrix-Portal-M4#how-to-build-the-firmware-using-the-arduino-ide). 

Getting the following compilation error after installing the libraries specified in this section:
```/Users/brentrubell/Documents/Arduino/libraries/ExpressivePixelsArduinoPlatformLibrary/EPXPlatform_Runtime.cpp:8:10: fatal error: SEGGER_RTT.h: No such file or directory
Alternatives for SEGGER_RTT.h: []
    8 | #include <SEGGER_RTT.h>
ResolveLibrary(SEGGER_RTT.h)
      |          ^~~~~~~~~~~~~~
  -> candidates: []```

**Comment by brentru** [comment]
Seems to be commented out here: https://github.com/microsoft/ExpressivePixels/blob/master/Firmware/Platform_Arduino/EPXPlatform_Runtime.h#L5

Could this be moved to the `config.h` file instead (default to commented out) so users can define a hardware debugger from there instead of from within the library?

**Comment by GJSea** [comment]
Hi @brentru , ahh yes I'm surprised its pulling the header in as that #ifdef in the CPP should prevent that, have you managed to coerce the build forward?. I didn't elevate its control any higher as it was purely a mechanism to introduce some level of trace diagnosis in the awful Arduino environment.

**Comment by brentru** [comment]
Pulled the latest `master` and seems to have resolved. 

>  I didn't elevate its control any higher as it was purely a mechanism to introduce some level of trace diagnosis in the awful Arduino environment.

Yep, understandable!
